---
- name: Deploy Application
  hosts: local
  become: yes
  tasks:
    
    - name: Ensure Docker Compose is installed
      become: yes
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy Docker Compose file to server
      become: yes
      copy:
        src:  /home/ziyaurraheman/Downloads/full-stack-estate-main/docker-compose.yml
        dest: /home/ziyaurraheman/Downloads/full-stack-estate-main/docker-compose.yml

    - name: Start Docker Compose services
      become: yes
      command: docker-compose -f /home/ziyaurraheman/Downloads/full-stack-estate-main/docker-compose.yml up -d
